spring:
  application:
    name: Craftly

  jackson:
    time-zone: UTC   # optional but recommended

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB?currentSchema=public
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

jwt:
  secret-key: as9bsjbhjccibiduiw983bdbcc9hn2bbic92hcnc9829hedcnhh
